/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import controllers.DbConnection;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import shopcenter.models.Product;

/**
 *
 * @author youssef
 */
public class EditItem extends javax.swing.JFrame implements Ui{

    /**
     * Creates new form EditItem
     */
    Product p;
    DbConnection db;

    public EditItem() {
        db=DbConnection.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categorytxtfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qauntitytxtfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pricetxtfield = new javax.swing.JTextField();
        discounttxtfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nametxtfeild = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idtxtfield = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Qauntity");

        jLabel4.setText("Price");

        jLabel5.setText("Discount");

        jLabel1.setText("Name");

        jButton1.setText("Pickimage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Category");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("id");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nametxtfeild)
                                            .addComponent(categorytxtfield)
                                            .addComponent(qauntitytxtfield)
                                            .addComponent(pricetxtfield)
                                            .addComponent(discounttxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                        .addComponent(jButton5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jButton1)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(51, 51, 51)
                        .addComponent(jButton4)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nametxtfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton5)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categorytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qauntitytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pricetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(discounttxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filename;
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon img=new ImageIcon(new ImageIcon(filename).getImage().
            getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH ) );
        image.setIcon(img);
        try {
            FileInputStream  fis=new FileInputStream(f);
            ByteArrayOutputStream boas= new  ByteArrayOutputStream();
            byte[] buff=new byte[1024];
            for(int r;(r=fis.read(buff))!=0;){
                boas.write(buff,0,r);
            }
            p.setImage(boas.toByteArray());
        } catch (IOException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idtxt=idtxtfield.getText();
        if(!idtxt.isEmpty()){
             
             try {
                int id=Integer.parseInt(idtxt);
                Product temp=db.getproductbyid(id);
                if(temp.getId()!=0){
                      db.deleteProduct(id);
                      JOptionPane.showMessageDialog(this,
                    "item deleted");
                      dispose();
                }
                else{
                      JOptionPane.showMessageDialog(this,
                    "id not found");
                }
            } catch (Exception e) {
                   JOptionPane.showMessageDialog(this,
        "please enter valid numer");
            }
        }
        else{
              JOptionPane.showMessageDialog(this,
        "you must search item first");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String idtxt=idtxtfield.getText();
      String name=nametxtfeild.getText();
      if(!idtxt.isEmpty()){
        try{
             
                int id=Integer.parseInt(idtxt);
                p=db.getproductbyid(id);
                if(p.getId()!=0)
                    updateui();
                else{
                    JOptionPane.showMessageDialog(this,
                            "not found");
                }
             }catch(Exception e){
                    JOptionPane.showMessageDialog(this,
        "Please Enter valid number");
             }
      }
      else if(!name.isEmpty()){
         p=db.getproductbyTitle(name);
         if(p.getId()!=0)
              updateui();
         else{
             JOptionPane.showMessageDialog(this,
                    "not found");
         }
      }
      else{
           JOptionPane.showMessageDialog(this,
                    "can only search with name or id");
      }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String idtxt=idtxtfield.getText();
        if(!idtxt.isEmpty()){
             
             try {
                int id=Integer.parseInt(idtxt);
                Product temp=db.getproductbyid(id);
                if(temp.getId()!=0){
                      trytoedit();
                     
                }
                else{
                      JOptionPane.showMessageDialog(this,
                    "id not found");
                }
            } catch (Exception e) {
                   JOptionPane.showMessageDialog(this,
        "please enter valid numer");
            }
        }
        else{
              JOptionPane.showMessageDialog(this,
        "you must search item first");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void updateui() {
        idtxtfield.setText(Integer.toString(p.getId()));
        nametxtfeild.setText(p.getTitle());
        categorytxtfield.setText(p.getCategory());
        discounttxtfield.setText(Float.toString(p.getDiscount()));
        pricetxtfield.setText(Float.toString(p.getPrice()));
        qauntitytxtfield.setText(Integer.toString(p.getQauntity()));
        ImageIcon img=new ImageIcon(new ImageIcon(p.getImage()).getImage().
        getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH ) );
        image.setIcon(img);
       }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categorytxtfield;
    private javax.swing.JTextField discounttxtfield;
    private javax.swing.JTextField idtxtfield;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nametxtfeild;
    private javax.swing.JTextField pricetxtfield;
    private javax.swing.JTextField qauntitytxtfield;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showui() {
        initComponents();
        setVisible(true);
    
    }

    private void trytoedit() {
          String name=nametxtfeild.getText();
             String category=categorytxtfield.getText();
             String pricetxt=pricetxtfield.getText();
             String qauntitytxt=qauntitytxtfield.getText();
             String discounttxt=discounttxtfield.getText();
             try{
                float price=Float.parseFloat(pricetxt);
                int qauntity=Integer.parseInt(qauntitytxt);
                float discount=Float.parseFloat(discounttxt);
                p.setTitle(name);
                p.setDiscount(discount);
                p.setCategory(category);
                p.setPrice(price);
                p.setQauntity(qauntity);
                if(checkinputs()){
                  db.updateproduct(p);
                   JOptionPane.showMessageDialog(this,
                    "item edited");
                }
             }catch(Exception e){
                    JOptionPane.showMessageDialog(this,
        "Please Enter valid number");
             }
    }

    private boolean checkinputs() {
        if(p.getTitle()==null||p.getTitle().isEmpty()){
          JOptionPane.showMessageDialog(this,
        "Please Enter a valid name");
          return false;
        }
        if(p.getCategory()==null||p.getCategory().isEmpty()||!db.checkcategoryexsits(p.getCategory())){
           JOptionPane.showMessageDialog(this,
        "Please Enter exist category_name");
           return false;
        }
        if(p.getDiscount()>=1.00||p.getDiscount()<=0.0){
            JOptionPane.showMessageDialog(this,
        "Please Enter value between 0.0 and 1.0 in discount");
           return false;
        }
         if(p.getImage()==null){
            JOptionPane.showMessageDialog(this,
        "Please pick image");
           return false;
        }
        return true;
    }

   
}
